# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # step useless, flex & bison already installed on github actions servers
    #- name: Install dependencies
    #  run: sudo apt-get update && sudo apt-get install -y flex bison

    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" "-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}"

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config "${{env.BUILD_TYPE}}"

